### ISSUE TITLE
Initial inoculum intensity parameter not used

### ISSUE THREAD

**Issue by IhsanKhaliq** [IhsanKhaliq/valascotraceR#8]
I think the `Initial inoculum intensity` need to included in the `ascotraceR` so the `valascotraceR` can recognise it. Getting an error 
`Error in { : 
  task 1 failed - "unused argument (initial_inoculum_intensity = 1)"`
 

https://github.com/IhsanKhaliq/valascotraceR/blob/f69e838f3899e59156669cb9aebe9d3624b18c78/example_trace_ascoRun.Rmd#L93

**Comment by adamhsparks** [comment]
I thought this was removed from _ascotraceR_ for submission to CRAN. Why on earth are we putting it back after all the discussion we had on the topic?

**Comment by IhsanKhaliq** [comment]
![Screen Shot 2021-12-21 at 11 00 51 am](https://user-images.githubusercontent.com/54728693/146853184-2461af09-931c-456a-86e5-729791313762.png)

**Comment by adamhsparks** [comment]
What does it even mean? The model just runs starting from the initial number of infective sites. AFAIK it doesn't distinguish between inoculum sources.

**Comment by IhsanKhaliq** [comment]
It's not related to inoculum sources. It's related to the number of infected quadrats on the date of initial infection. We have currently have an open issue #7

**Comment by adamhsparks** [comment]
then why is it called `initial_inoculum_intensity`? That's related to inoculum.

**Comment by IhsanKhaliq** [comment]
We can call it `initial_infection_intensity` instead, but it's still not used. We have the same number of foci. It's not about the number of foci. It's about the number of infected quadrats at the time of initial infection

**Comment by PaulMelloy** [comment]
Have you reinstalled the latest version?

**Comment by IhsanKhaliq** [comment]
Yes, I `Install and Restart` package locally before visiting `valascotraceR`.

**Comment by PaulMelloy** [comment]
do you mean `primary_inoculum_intensity`

**Comment by PaulMelloy** [comment]
as you mention `initial_infection_intensity` is not a argument in the model, the argument you might be looking for is `primary_inoculum_intensity`

**Comment by IhsanKhaliq** [comment]
No `primary_inoculum_intensity` works (these are lesions on infested stubble). I am talking about issue #7 (number of infected quadrats at the time of initial infection)

**Comment by PaulMelloy** [comment]
We decided to remove that as per the email. You agreed on it.
See the documentation for what `primary_inoculum_intensity` means

```r
#' primary_inoculum_intensity Refers to the amount of primary infection
#'   as lesions on chickpea plants at the time of `initial_infection`. On the
#'   date of initial infection in the experiment. The sources of primary
#'   inoculum can be infected seed, volunteer chickpea plants or infested
#'   stubble from the previous seasons. Defaults to `1`.
```

**Comment by IhsanKhaliq** [comment]
We agreed on removing stubble sources. See the highlited bit
![Screen Shot 2021-12-21 at 11 27 52 am](https://user-images.githubusercontent.com/54728693/146855199-2278a12c-bc61-4723-b5dd-b2531e0c532c.png)

**Comment by IhsanKhaliq** [comment]
What's the solution now? We need to wrap up things. My aim is not to make things complicated

![Screen Shot 2021-12-21 at 11 30 25 am](https://user-images.githubusercontent.com/54728693/146855441-1be0af76-a118-439f-8dea-c04f774820b2.png)

**Comment by PaulMelloy** [comment]
The fact this has gone on so long makes it clear that I don't understand what the issue is. I have more than exhausted my time working on this package and have other pressing demands.
As this is your work I advise you spend some time correcting this issue, and making the changes you require.

**Comment by IhsanKhaliq** [comment]
I corrected the definition here a3754c6ac843a12e7cd88536f285975103f98658 , but it got reverted. I have also reached my tipping point with this

**Comment by IhsanKhaliq** [comment]
f2867f6

**Comment by IhsanKhaliq** [comment]
Do I put this back this back there?
https://github.com/IhsanKhaliq/ascotraceR/commit/a3754c6ac843a12e7cd88536f285975103f98658

**Comment by IhsanKhaliq** [comment]
Issue #7 will still remain though

**Comment by IhsanKhaliq** [comment]
Closed by changing the definition of `primary_inoculum_intensity` to represent `primary inoculum` not `primary infection`. We still need to introduce a parameter `primary_infection_intensity` to include the number of infected quadrats (`primary infection`) at the time of initial infection, as discussed issue #7
